/* Generated By:JavaCC: Do not edit this line. SwitchConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SwitchConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 3;
  /** RegularExpression Id. */
  int WHILE = 4;
  /** RegularExpression Id. */
  int IF = 5;
  /** RegularExpression Id. */
  int ELSE = 6;
  /** RegularExpression Id. */
  int SWITCH = 7;
  /** RegularExpression Id. */
  int CASE = 8;
  /** RegularExpression Id. */
  int COLON = 9;
  /** RegularExpression Id. */
  int DEFLT = 10;
  /** RegularExpression Id. */
  int BREAK = 11;
  /** RegularExpression Id. */
  int INT = 12;
  /** RegularExpression Id. */
  int VOID = 13;
  /** RegularExpression Id. */
  int LETTER = 14;
  /** RegularExpression Id. */
  int IDENT = 15;
  /** RegularExpression Id. */
  int DIGIT = 16;
  /** RegularExpression Id. */
  int NUMBER = 17;
  /** RegularExpression Id. */
  int PLUS = 18;
  /** RegularExpression Id. */
  int MINUS = 19;
  /** RegularExpression Id. */
  int TIMES = 20;
  /** RegularExpression Id. */
  int DIV = 21;
  /** RegularExpression Id. */
  int PERCENT = 22;
  /** RegularExpression Id. */
  int OPAR = 23;
  /** RegularExpression Id. */
  int CPAR = 24;
  /** RegularExpression Id. */
  int OBRA = 25;
  /** RegularExpression Id. */
  int CBRA = 26;
  /** RegularExpression Id. */
  int EQU = 27;
  /** RegularExpression Id. */
  int LEQU = 28;
  /** RegularExpression Id. */
  int GEQU = 29;
  /** RegularExpression Id. */
  int LESS = 30;
  /** RegularExpression Id. */
  int GREAT = 31;
  /** RegularExpression Id. */
  int NEQU = 32;
  /** RegularExpression Id. */
  int NOT = 33;
  /** RegularExpression Id. */
  int AND = 34;
  /** RegularExpression Id. */
  int OR = 35;
  /** RegularExpression Id. */
  int ASSIGN = 36;
  /** RegularExpression Id. */
  int COMMA = 37;
  /** RegularExpression Id. */
  int SEMICOL = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<EOL>",
    "\"while\"",
    "\"if\"",
    "\"else\"",
    "\"switch\"",
    "\"case\"",
    "\":\"",
    "\"default\"",
    "\"break\"",
    "\"int\"",
    "\"void\"",
    "<LETTER>",
    "<IDENT>",
    "<DIGIT>",
    "<NUMBER>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"<\"",
    "\">\"",
    "\"!=\"",
    "\"!\"",
    "\"&&\"",
    "\"||\"",
    "\"=\"",
    "\",\"",
    "\";\"",
  };

}
